"""Add iframe_url to Game model

Revision ID: 550316ec46d9
Revises: 
Create Date: 2025-09-16 16:26:04.078143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '550316ec46d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('iframe_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('iframe_url')

    # ### end Alembic commands ###
